# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tuanna47/VOIP/voip_patrol

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tuanna47/VOIP/voip_patrol

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tuanna47/VOIP/voip_patrol/CMakeFiles /home/tuanna47/VOIP/voip_patrol/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tuanna47/VOIP/voip_patrol/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named voip_patrol

# Build rule for target.
voip_patrol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 voip_patrol
.PHONY : voip_patrol

# fast build rule for target.
voip_patrol/fast:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/build
.PHONY : voip_patrol/fast

src/ezxml/ezxml.o: src/ezxml/ezxml.c.o

.PHONY : src/ezxml/ezxml.o

# target to build an object file
src/ezxml/ezxml.c.o:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/ezxml/ezxml.c.o
.PHONY : src/ezxml/ezxml.c.o

src/ezxml/ezxml.i: src/ezxml/ezxml.c.i

.PHONY : src/ezxml/ezxml.i

# target to preprocess a source file
src/ezxml/ezxml.c.i:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/ezxml/ezxml.c.i
.PHONY : src/ezxml/ezxml.c.i

src/ezxml/ezxml.s: src/ezxml/ezxml.c.s

.PHONY : src/ezxml/ezxml.s

# target to generate assembly for a file
src/ezxml/ezxml.c.s:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/ezxml/ezxml.c.s
.PHONY : src/ezxml/ezxml.c.s

src/voip_patrol/action.o: src/voip_patrol/action.cc.o

.PHONY : src/voip_patrol/action.o

# target to build an object file
src/voip_patrol/action.cc.o:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/action.cc.o
.PHONY : src/voip_patrol/action.cc.o

src/voip_patrol/action.i: src/voip_patrol/action.cc.i

.PHONY : src/voip_patrol/action.i

# target to preprocess a source file
src/voip_patrol/action.cc.i:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/action.cc.i
.PHONY : src/voip_patrol/action.cc.i

src/voip_patrol/action.s: src/voip_patrol/action.cc.s

.PHONY : src/voip_patrol/action.s

# target to generate assembly for a file
src/voip_patrol/action.cc.s:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/action.cc.s
.PHONY : src/voip_patrol/action.cc.s

src/voip_patrol/check.o: src/voip_patrol/check.cc.o

.PHONY : src/voip_patrol/check.o

# target to build an object file
src/voip_patrol/check.cc.o:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/check.cc.o
.PHONY : src/voip_patrol/check.cc.o

src/voip_patrol/check.i: src/voip_patrol/check.cc.i

.PHONY : src/voip_patrol/check.i

# target to preprocess a source file
src/voip_patrol/check.cc.i:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/check.cc.i
.PHONY : src/voip_patrol/check.cc.i

src/voip_patrol/check.s: src/voip_patrol/check.cc.s

.PHONY : src/voip_patrol/check.s

# target to generate assembly for a file
src/voip_patrol/check.cc.s:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/check.cc.s
.PHONY : src/voip_patrol/check.cc.s

src/voip_patrol/mod_voip_patrol.o: src/voip_patrol/mod_voip_patrol.cc.o

.PHONY : src/voip_patrol/mod_voip_patrol.o

# target to build an object file
src/voip_patrol/mod_voip_patrol.cc.o:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/mod_voip_patrol.cc.o
.PHONY : src/voip_patrol/mod_voip_patrol.cc.o

src/voip_patrol/mod_voip_patrol.i: src/voip_patrol/mod_voip_patrol.cc.i

.PHONY : src/voip_patrol/mod_voip_patrol.i

# target to preprocess a source file
src/voip_patrol/mod_voip_patrol.cc.i:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/mod_voip_patrol.cc.i
.PHONY : src/voip_patrol/mod_voip_patrol.cc.i

src/voip_patrol/mod_voip_patrol.s: src/voip_patrol/mod_voip_patrol.cc.s

.PHONY : src/voip_patrol/mod_voip_patrol.s

# target to generate assembly for a file
src/voip_patrol/mod_voip_patrol.cc.s:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/mod_voip_patrol.cc.s
.PHONY : src/voip_patrol/mod_voip_patrol.cc.s

src/voip_patrol/voip_patrol.o: src/voip_patrol/voip_patrol.cc.o

.PHONY : src/voip_patrol/voip_patrol.o

# target to build an object file
src/voip_patrol/voip_patrol.cc.o:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/voip_patrol.cc.o
.PHONY : src/voip_patrol/voip_patrol.cc.o

src/voip_patrol/voip_patrol.i: src/voip_patrol/voip_patrol.cc.i

.PHONY : src/voip_patrol/voip_patrol.i

# target to preprocess a source file
src/voip_patrol/voip_patrol.cc.i:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/voip_patrol.cc.i
.PHONY : src/voip_patrol/voip_patrol.cc.i

src/voip_patrol/voip_patrol.s: src/voip_patrol/voip_patrol.cc.s

.PHONY : src/voip_patrol/voip_patrol.s

# target to generate assembly for a file
src/voip_patrol/voip_patrol.cc.s:
	$(MAKE) -f CMakeFiles/voip_patrol.dir/build.make CMakeFiles/voip_patrol.dir/src/voip_patrol/voip_patrol.cc.s
.PHONY : src/voip_patrol/voip_patrol.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... voip_patrol"
	@echo "... src/ezxml/ezxml.o"
	@echo "... src/ezxml/ezxml.i"
	@echo "... src/ezxml/ezxml.s"
	@echo "... src/voip_patrol/action.o"
	@echo "... src/voip_patrol/action.i"
	@echo "... src/voip_patrol/action.s"
	@echo "... src/voip_patrol/check.o"
	@echo "... src/voip_patrol/check.i"
	@echo "... src/voip_patrol/check.s"
	@echo "... src/voip_patrol/mod_voip_patrol.o"
	@echo "... src/voip_patrol/mod_voip_patrol.i"
	@echo "... src/voip_patrol/mod_voip_patrol.s"
	@echo "... src/voip_patrol/voip_patrol.o"
	@echo "... src/voip_patrol/voip_patrol.i"
	@echo "... src/voip_patrol/voip_patrol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

